### ISSUE TITLE
poly_pkt_fwd no such file or directory

### ISSUE THREAD

**Issue by ghost** [ttn-zh/ic880a-gateway#13]
I followed the instructions and when I launch start.sh I get:
`
./start.sh: line 43: ./poly_pkt_fwd: No such file or directory`

**Comment by gonzalocasas** [comment]
Hi @fabio-C, something must be wrong because at no point are you supposed to lauch `start.sh` manually.
Why did you end up running it manually? Is the systemd process not running?

**Comment by ghost** [comment]
After launch "install.sh" what is the next step? Does the gateway software start automatically?

**Comment by gonzalocasas** [comment]
Yes. Install creates a systemd service, you can query the status of the service using normal systemd commands, the service is called `ttn-gateway`. You can also use journalctl to check logs of that specific unit (or just grep `syslog`)

**Comment by gonzalocasas** [comment]
Closing until we get more details from @fabio-C

**Comment by Hitheshkaranth** [comment]
@gonzalocasas 
Greeting I'm encoutering the same problem. 

This is the log I get when I run start.sh

*** Poly Packet Forwarder for Lora Gateway ***
Version: 2.1.0
*** Lora concentrator HAL library version info ***
Version: 3.1.0; Options: native;
***
INFO: Little endian host
INFO: found global configuration file global_conf.json, parsing it
INFO: global_conf.json does contain a JSON object named SX1301_conf, parsing SX1301 parameters
INFO: lorawan_public 1, clksrc 1
INFO: Configuring TX LUT with 16 indexes
INFO: radio 0 enabled (type SX1257), center frequency 867500000, RSSI offset -166.000000, tx enabled 1
INFO: radio 1 enabled (type SX1257), center frequency 868500000, RSSI offset -166.000000, tx enabled 0
INFO: Lora multi-SF channel 0>  radio 1, IF -400000 Hz, 125 kHz bw, SF 7 to 12
INFO: Lora multi-SF channel 1>  radio 1, IF -200000 Hz, 125 kHz bw, SF 7 to 12
INFO: Lora multi-SF channel 2>  radio 1, IF 0 Hz, 125 kHz bw, SF 7 to 12
INFO: Lora multi-SF channel 3>  radio 0, IF -400000 Hz, 125 kHz bw, SF 7 to 12
INFO: Lora multi-SF channel 4>  radio 0, IF -200000 Hz, 125 kHz bw, SF 7 to 12
INFO: Lora multi-SF channel 5>  radio 0, IF 0 Hz, 125 kHz bw, SF 7 to 12
INFO: Lora multi-SF channel 6>  radio 0, IF 200000 Hz, 125 kHz bw, SF 7 to 12
INFO: Lora multi-SF channel 7>  radio 0, IF 400000 Hz, 125 kHz bw, SF 7 to 12
INFO: Lora std channel> radio 1, IF -200000 Hz, 250000 Hz bw, SF 7
INFO: FSK channel> radio 1, IF 300000 Hz, 125000 Hz bw, 50000 bps datarate
INFO: global_conf.json does contain a JSON object named gateway_conf, parsing gateway parameters
INFO: gateway MAC address is configured to AA555A0000000000
INFO: Found 2 servers in array.
INFO: Server 0 configured to "127.0.0.1", with port up "1680" and port down "1681"
INFO: Server 1 configured to "iot.semtech.com", with port up "1680" and port down "1680"
INFO: Found 5 system calls in array.
INFO: System command 0: "df -m"
INFO: System command 1: "free -h"
INFO: System command 2: "uptime"
INFO: System command 3: "who -a"
INFO: System command 4: "uname -a"
INFO: monitor hostname or IP address is configured to "127.0.0.1"
INFO: monitor port is configured to "2008"
INFO: ghost hostname or IP address is configured to "127.0.0.1"
INFO: ghost port is configured to "1918"
INFO: downstream keep-alive interval is configured to 10 seconds
INFO: statistics display interval is configured to 30 seconds
INFO: upstream PUSH_DATA time-out is configured to 100 ms
INFO: packets received with a valid CRC will be forwarded
INFO: packets received with a CRC error will NOT be forwarded
INFO: packets received with no CRC will NOT be forwarded
INFO: GPS serial port path is configured to "/dev/ttyAMA0"
INFO: SSH path is configured to "/usr/bin/ssh"
INFO: SSH port is configured to 22
INFO: HTTP port is configured to 80
INFO: NGROK path is configured to "/usr/bin/ngrok"
INFO: Reference latitude is configured to 10.000000 deg
INFO: Reference longitude is configured to 20.000000 deg
INFO: Reference altitude is configured to -1 meters
INFO: GPS is enabled
INFO: Using fake GPS coordinates instead of real.
INFO: antenna_gain 0 dBi
INFO: Upstream data is enabled
INFO: Downstream data is enabled
INFO: Ghoststream data is disabled
INFO: Radiostream data is enabled
INFO: Statusstream data is enabled
INFO: Beacon is disabled
INFO: Monitor is disabled
INFO: Platform configured to "IMST + Rpi"
INFO: Contact email configured to "operator@gateway.tst"
INFO: Description configured to "Update me"
INFO: found local configuration file local_conf.json, parsing it
INFO: redefined parameters will overwrite global parameters
INFO: local_conf.json does not contain a JSON object named SX1301_conf
INFO: local_conf.json does contain a JSON object named gateway_conf, parsing gateway parameters
INFO: gateway MAC address is configured to AA555A000004BABA
INFO: packets received with a valid CRC will be forwarded
INFO: packets received with a CRC error will NOT be forwarded
INFO: packets received with no CRC will NOT be forwarded
INFO: GPS is enabled
INFO: antenna_gain 0 dBi
INFO: Upstream data is enabled
INFO: Downstream data is enabled
INFO: Ghoststream data is disabled
INFO: Radiostream data is enabled
INFO: Statusstream data is enabled
INFO: Beacon is disabled
INFO: Monitor is disabled
INFO: Successfully contacted server 127.0.0.1
INFO: Successfully contacted server iot.semtech.com
INFO: [main] Starting the concentrator
ERROR: [main] failed to start the concentrator

**Comment by gonzalocasas** [comment]
@Hitheshkaranth as I said above, you're not supposed to run start manually, it runs as a service so triggering it by hand will not work as expected.

On the other hand, your log has nothing to do with the one in the original comment. What makes you think it's the same?

**Comment by Hitheshkaranth** [comment]
Greetings,

Thanks for replying. I am stuck with the concentrator not starting and has
no idea how to start it. Can you guide me how to set this up?

**Comment by gonzalocasas** [comment]
Check if you really have SPI enabled
Check if the power supply is enough (at least 2A!)
Check if there's no hardware damage
Then check the proper logs, don't try running the service by hand, use
syslog or journalctl to see the log output of the service.

**Comment by Hitheshkaranth** [comment]
I apologize for late reply,

1.Yes,SPI is enabled on my board
2.Yes,the power source is ample enough
3.Yes but no sign of LoRa gate way turning on I viewed it on journalctl no
sign of services related to lora.

ERROR: [main] failed to start the concentrator

every time I try to run it this seems to be the error thrown up.

**Comment by gonzalocasas** [comment]
> 3.Yes but no sign of LoRa gate way turning on I viewed it on journalctl no sign of services related to lora.

If there's really no sign of ttn-gateway service on `journalctl` then you have a misconfiguration. Please start on a clean image and re-install to be sure. 

> every time I try to run it this seems to be the error thrown up.

As I said, if you're running it manually, something is wrong in your installation, because this runs as a service.
