### ISSUE TITLE
Not sending after wifi reset

### ISSUE THREAD

**Issue by rudybeset** [ttn-zh/ic880a-gateway#73]
Hi, i have build this project with Pi3B and it is working fine.
But when the gateway is powered-on, and the wifi AP is not there, while the gateway tryes to send packages to TTN.
It fails because wifi is not connected to AP. 
So far, this is normal, but when wifi is restored, no packages get send anymore.
Even reboot of the Pi will not make it send packages to the TTN. Lora gets data in, wifi is connected to the internet, but no packages get send anymore,
Only solution so far is reflash the SD card.

**Comment by gonzalocasas** [comment]
This is not a problem of the package forwarder or of this installer, if it doesn't work after a restart, I assume you have a problem in your network, maybe something is blocking udp connections. I will close this issue, because there's nothing to change on this repo to solve this, but you're free to keep commenting on the issue anyway.
